version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=${API_URL}
      - REACT_APP_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - API_PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
