version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: certbot/Dockerfile
    volumes:
      - ./build:/usr/share/nginx/html
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - API_PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - frontend
      - api

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${ADMIN_EMAIL} -d ${DOMAIN_NAME} -d www.${DOMAIN_NAME} --agree-tos

volumes:
  certbot_conf:
  certbot_www:
